### ISSUE TITLE
[FR] pademu support

### ISSUE THREAD

**Issue by ildar** [TnA-Plastic/FreeMcBoot#4]
Pademu from OPL project is a great feature. FMCB might also benefit from it allowing to use PS2 without PS2 joysticks! :)

**Comment by ildar** [comment]
em, with all respect to @sp193 ! Liu, what do you think?

**Comment by ildar** [comment]
sorry, Liu!

**Comment by TnA-Plastic** [comment]
Sure, it is possible and also 'on the list' of things which might get added later.

However, there are currently other more important things, IMO.

Support for other controller-types is rather a ' convenience-thing'...

**Comment by ildar** [comment]
Yep, sure. Let it be a pending feature request :)

**Comment by TnA-Plastic** [comment]
Just for reference, I created a Project about it (along some others)! ;)

Btw.: Check out @SP193's newest update to FMCB/FHDB (1.966)! ;)

**Comment by ildar** [comment]
пт, 11 янв. 2019 г. в 06:07, TnA-Plastic:

> Just for reference, I created a Project about it (along some others)! ;)
>
👍

> Btw.: Check out @sp193 <https://github.com/sp193>'s newest update to
> FMCB/FHDB (1.966)! ;)
>
Can't find @sp193 <https://github.com/sp193>'s source code. Hope you can
merge his changes.

**Comment by TnA-Plastic** [comment]
@SP193 released the source of the installer, but not the loader (as of yet).
